In [1]:
# Python program to implement a 
# single neuron neural network 

# import all necessery libraries 
from numpy import exp, array, random, dot, tanh 

# Class to create a neural 
# network with single neuron 
class NeuralNetwork(): 
	
	def __init__(self): 
		
		# Using seed to make sure it'll 
		# generate same weights in every run 
		random.seed(1) 
		
		# 3x1 Weight matrix 
		self.weight_matrix = 2 * random.random((3, 1)) - 1

	# tanh as activation function 
	def tanh(self, x): 
		return tanh(x) 

	# derivative of tanh function. 
	# Needed to calculate the gradients. 
	def tanh_derivative(self, x): 
		return 1.0 - tanh(x) ** 2

	# forward propagation 
	def forward_propagation(self, inputs): 
		return self.tanh(dot(inputs, self.weight_matrix)) 
	
	# training the neural network. 
	def train(self, train_inputs, train_outputs, 
							num_train_iterations): 
								
		# Number of iterations we want to 
		# perform for this set of input. 
		for iteration in range(num_train_iterations): 
			output = self.forward_propagation(train_inputs) 

			# Calculate the error in the output. 
			error = train_outputs - output 

			# multiply the error by input and then 
			# by gradient of tanh funtion to calculate 
			# the adjustment needs to be made in weights 
			adjustment = dot(train_inputs.T, error *
							self.tanh_derivative(output)) 
							
			# Adjust the weight matrix 
			self.weight_matrix += adjustment 

# Driver Code 
if __name__ == "__main__": 
	
	neural_network = NeuralNetwork() 
	
	print ('Random weights at the start of training') 
	print (neural_network.weight_matrix) 

	train_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]]) 
	train_outputs = array([[0, 1, 1, 0]]).T 

	neural_network.train(train_inputs, train_outputs, 10000) 

	print ('New weights after training') 
	print (neural_network.weight_matrix) 

	# Test the neural network with a new situation. 
	print ("Testing network on new examples ->") 
	print (neural_network.forward_propagation(array([1, 0, 0]))) 


Random weights at the start of training
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
New weights after training
[[5.39428067]
 [0.19482422]
 [0.34317086]]
Testing network on new examples ->
[0.99995873]


In [2]:
import pandas as pd

# Location of dataset
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
irisdata = pd.read_csv(url, names=names)

In [3]:
irisdata.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
# Assign data from first four columns to X variable
X = irisdata.iloc[:, 0:4]

# Assign data from first fifth columns to y variable
y = irisdata.select_dtypes(include=[object])

In [5]:
y.Class.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

y = y.apply(le.fit_transform)

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, y_train.values.ravel())

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(10, 10, 10), learning_rate='constant',
       learning_rate_init=0.001, max_iter=1000, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [11]:
predictions = mlp.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[ 9  0  0]
 [ 0 12  0]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      1.00      1.00        12
           2       1.00      1.00      1.00         9

   micro avg       1.00      1.00      1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

